version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quack
      POSTGRES_PASSWORD: quack
      POSTGRES_DB: quack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quack"]
      interval: 2s
      timeout: 1s
      retries: 20

  prisma_preview:
    build:
      context: ./backend
      dockerfile: ../scripts/prisma.dockerfile
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
